// Builds a standalone Tabletop Simulator "Saved Object" file containing one
// DeckCustom per generated deck sheet, so it shows up in TTS's Saved Objects
// library ready to drag onto a table. Ported from dune_board_game/v2's
// update_in_tts.py (build_deck / build_save / generate_tts_save).

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

function guid() {
  return crypto.randomBytes(4).toString("hex").slice(0, 6);
}

// 510, 511, 512... kept close to IDs already observed in John Company saves.
function makeDeckId(deckIndex) {
  return 510 + deckIndex;
}

// TTS convention: 51300, 51301, ... 51334
function makeCardId(customDeckId, cardIndex) {
  return customDeckId * 100 + cardIndex;
}

function buildCustomDeckEntry(deck, width, height) {
  return {
    FaceURL: deck.front,
    BackURL: deck.back,
    NumWidth: width,
    NumHeight: height,
    Number: deck.number,
    BackIsHidden: true,
    UniqueBack: true,
    Type: 0,
  };
}

function buildCard(cardId, originX, originZ, scale = 1) {
  return {
    GUID: guid(),
    Name: "Card",
    Transform: {
      posX: originX, posY: 1, posZ: originZ,
      rotX: 0, rotY: 180, rotZ: 0,
      scaleX: scale, scaleY: 1, scaleZ: scale,
    },
    Nickname: "",
    Description: "",
    GMNotes: "",
    AltLookAngle: { x: 0, y: 0, z: 0 },
    ColorDiffuse: { r: 0.713235259, g: 0.713235259, b: 0.713235259 },
    LayoutGroupSortIndex: 0,
    Value: 0,
    Locked: false,
    Grid: true,
    Snap: true,
    IgnoreFoW: false,
    MeasureMovement: false,
    DragSelectable: true,
    Autoraise: true,
    Sticky: true,
    Tooltip: true,
    GridProjection: false,
    Hands: true,
    CardID: cardId,
    SidewaysCard: false,
    XmlUI: "",
  };
}

function buildDeck(deck, deckIndex, originX = 0, originZ = 0) {
  const { width, height, number: total, scale = 1 } = deck;
  const customDeckId = makeDeckId(deckIndex);
  const customDeck = { [customDeckId]: buildCustomDeckEntry(deck, width, height) };

  const deckIds = [];
  const cards = [];
  for (let i = 0; i < total; i++) {
    const cardId = makeCardId(customDeckId, i);
    deckIds.push(cardId);
    cards.push(buildCard(cardId, originX, originZ, scale));
  }

  return {
    GUID: guid(),
    Name: "DeckCustom",
    Transform: {
      posX: originX, posY: 1.2, posZ: originZ,
      rotX: 0, rotY: 180, rotZ: 0,
      scaleX: scale, scaleY: 1, scaleZ: scale,
    },
    Nickname: deck.name ?? "",
    Description: "",
    GMNotes: "",
    AltLookAngle: { x: 0, y: 0, z: 0 },
    ColorDiffuse: { r: 0.713235259, g: 0.713235259, b: 0.713235259 },
    LayoutGroupSortIndex: 0,
    Value: 0,
    Locked: false,
    Grid: true,
    Snap: true,
    IgnoreFoW: false,
    MeasureMovement: false,
    DragSelectable: true,
    Autoraise: true,
    Sticky: true,
    Tooltip: true,
    GridProjection: false,
    HideWhenFaceDown: false,
    Hands: false,
    DeckIDs: deckIds,
    CustomDeck: customDeck,
    SidewaysCard: false,
    ContainedObjects: cards,
    LuaScript: "",
    LuaScriptState: "",
    XmlUI: "",
  };
}

function buildSave(decks, saveName) {
  return {
    SaveName: saveName,
    Date: "",
    VersionNumber: "",
    GameMode: "",
    GameType: "",
    GameComplexity: "",
    Tags: [],
    Gravity: 0.5,
    PlayArea: 0.5,
    Table: "",
    Sky: "",
    Note: "Generated by scripts/build-tts-sheets.mjs",
    TabStates: {},
    LuaScript: "",
    LuaScriptState: "",
    XmlUI: "",
    ObjectStates: decks.map((deck, i) => buildDeck(deck, i, i * 6, 0)),
  };
}

/**
 * @param {Array<{name:string, front:string, back:string, width:number, height:number, number:number}>} decks
 * @param {string} saveName
 * @param {string} filePath - absolute path to write the .json save into
 */
export function generateTtsSave(decks, saveName, filePath) {
  const saveObj = buildSave(decks, saveName);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(saveObj, null, 2), "utf8");
  return filePath;
}
