// Copy this file to tts.config.local.mjs (already gitignored) and fill in
// your own values. See scripts/README.md for how to obtain each of these.
export default {
  googleDrive: {
    // A "Desktop app" OAuth client JSON downloaded from Google Cloud Console
    // (APIs & Services > Credentials). Reusing the same client dune_board_game
    // uses is fine — it's not tied to a single Drive folder.
    credentialsPath: "~/.ssh/keys/tts-card-uploader-secret.json",
    // Where the OAuth refresh token gets cached after the first interactive
    // login. Keep this out of git (it grants Drive access).
    tokenPath: "./scripts/.google-token.json",
    // The Drive folder (by ID, from its URL) that generated sheets get
    // uploaded into and made publicly readable.
    folderId: "PUT_YOUR_DRIVE_FOLDER_ID_HERE",
    scopes: ["https://www.googleapis.com/auth/drive.file"],
  },
  tts: {
    // Tabletop Simulator's "Saved Objects" library folder.
    savedObjectsPath: "~/Documents/My Games/Tabletop Simulator/Saves/Saved Objects",
    saveName: "AutoGeneratedJC2ETeaDecks",
  },
};
